POST https://localhost:7224/api/owner HTTP/1.1
Content-Type: application/json

{
    "code": "TEGMAN",
    "name": "Tegma Serviços LTDA",
    "document": "1212121",
    "typeDoc": "LegalPerson",
    "status": "Disabled"
}