PUT {{host}}/owner HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "code": "Tigre",
    "name": "Tigre Canos e PVC, LTDA.",
    "document": "34291311000100",
    "typeDoc": 1,
    "status": 2
}