POST http://localhost:5000/api/owner HTTP/1.1   
Content-Type: application/json

{
   "code": "OOPAL",
   "name": "OOPAL Serviços Diversos",
   "document": "00099898111",
   "customers": {
      "existingCustomers": [
         "7eebfb4a-bc10-4862-8e1b-e1d973f5ebae"
      ]
   }
}