POST http://localhost:5000/api/owner HTTP/1.1   
Content-Type: application/json

{
   "code": "OOAPAOS",
   "name": "OOAPAOS Serviços Diversos",
   "document": "18389182312",
   "customers": {
      "existingCustomers": [
         "77556dec-b497-48fa-8882-2292444eefa5"
      ],
      "newCustomers": [
         {
            "code": "LLAKS",
            "name": "LLAKS Serviços Diversos",
            "document": "00019919212"
         },
         {
            "code": "LLLAKKA",
            "name": "LLLAKKA Serviços Diversos",
            "document": "66615516151"
         }
      ]
   }
}

// {
//    "code": "OOPAL",
//    "name": "OOPAL Serviços Diversos",
//    "document": "00099898111",
//    "customers": {
//       "newCustomers": [
//          {
//             "code": "ALSLASA",
//             "name": "ALSLASA Serviços Diversos",
//             "document": "94817468621"
//          },
//          {
//             "code": "IIDLAKSDK",
//             "name": "IIDLAKSDK Serviços Diversos",
//             "document": "88572632711"
//          }
//       ]
//    }
// }