PUT https://localhost:7224/api/owner HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "code": "Tigre",
    "name": "Tigre Canos e PVC, LTDA.",
    "document": "19999911111100",
    "typeDoc": "LegalPerson",
    "status": "Activated"
}